package in.ansari.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;

/**
 * Persistent JPA entity that represents a course record stored in the database.
 * <p>
 * Instances of this class are mapped to the database table named "COURSES".
 * The class uses JPA annotations for ORM mapping and Lombok's {@code @Data}
 * to generate boilerplate getters, setters, {@code equals}, {@code hashCode}
 * and {@code toString} methods at compile time.
 * </p>
 * <p>
 * Typical usage: returned from repository queries, used as a DTO for persistence
 * operations, and transferred between service layers when working with course data.
 * </p>
 */

@Entity
@Table(name = "COURSES")
@Data
public class CourseEntity {

	/**
     * Primary key for the course record.
     * <p>
     * This value is generated by the persistence provider using the
     * {@link GenerationType#IDENTITY} strategy when a new row is inserted.
     * </p>
     * <p>
     * Type: {@link Integer}. May be {@code null} for transient (not-yet-persisted)
     * entities until the entity is saved and the database assigns a value.
     * </p>
     */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer courseId;
	
	/**
     * Human-readable name of the course.
     * <p>
     * This field holds the course title or short description used in UI and
     * reporting. It may be {@code null} if not set; validation rules (for example
     * non-null or length constraints) should be enforced at the service or
     * persistence layer if required by the application.
     * </p>
     */
	private String courseName;
}