package in.ansari.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;

/**
 * JPA entity representing an enquiry status stored in the database.
 * <p>
 * Mapped to the {@code ENQUIRY_STATUS} table, this entity models the possible
 * states an enquiry can have (for example: NEW, ENROLLED, LOST). Lombok's
 * {@code @Data} generates standard accessor methods, {@code equals}, {@code hashCode},
 * and {@code toString} implementations.
 * </p>
 * <p>
 * Use cases: returned by repository queries, referenced by enquiries to indicate
 * their current lifecycle state, and used in UI dropdowns or reports.
 * </p>
 */

@Entity
@Table(name = "ENQUIRY_STATUS")
@Data
public class EnquiryStatusEntity {

	/**
     * Primary key for the enquiry status.
     * <p>
     * Generated by the persistence provider using the
     * {@link GenerationType#IDENTITY} strategy when a new status row is persisted.
     * This field will be {@code null} for transient instances until persisted.
     * </p>
     */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer statusId;
	
	/**
     * Human-readable name of the status.
     * <p>
     * Examples: "NEW", "ENROLLED", "LOST". Validation rules such as
     * non-null or length constraints should be enforced by the service layer
     * or via additional JPA/Bean Validation annotations if required.
     * </p>
     */
	private String statusName;
}