package in.ansari.entity;

import java.time.LocalDate;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Data;
import lombok.ToString;

/**
 * JPA entity that models a student's enquiry record.
 * <p>
 * Instances are persisted to the {@code STUDENT_ENQUIRIES} table and capture
 * basic contact information, the course and class mode the student is interested in,
 * the current status of the enquiry, timestamps for creation and last update,
 * and an association to the user who recorded or owns the enquiry.
 * </p>
 * <p>
 * Lombok's {@code @Data} provides generated getters, setters, {@code equals},
 * {@code hashCode} and {@code toString}. The {@code @ToString} annotation excludes
 * the {@code userDetailsEntity} field to avoid unintentionally printing large or
 * sensitive user details and to prevent potential circular references.
 * </p>
 */

@Entity
@Table(name = "STUDENT_ENQUIRIES")
@Data
@ToString(exclude = "userDetailsEntity")
public class StudentEnquiryEntity {

	/**
     * Primary key for the enquiry.
     * <p>
     * Generated by the persistence provider using {@link GenerationType#IDENTITY}.
     * Will be {@code null} for transient instances until persisted.
     * </p>
     */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer enquiryId;
	
	/**
     * Full name of the student who made the enquiry.
     * <p>
     * This is intended for display and contact purposes. Validation (for example
     * non-null or length constraints) should be applied at the service or DTO layer
     * if required by the application.
     * </p>
     */
	private String studentName;
	
	/**
     * Contact phone number for the student.
     * <p>
     * Expected format is determined by application rules (for example local phone
     * format or E.164). This field may be used to reach out to the student for follow-up.
     * </p>
     */
	private String studentPhoneNumber;
	
	/**
     * Preferred class mode requested by the student.
     * <p>
     * Typical values might include "Online" and "Classroom" modes
     * defined by the business. Consider using an enum or reference table if the set
     * of modes is constrained.
     * </p>
     */
	private String classMode;
	
	/**
     * Name of the course the student is enquiring about.
     * <p>
     * This is a free-text course identifier; to preserve referential integrity
     * consider storing a course foreign key instead of or in addition to this field.
     * </p>
     */
	private String courseName;
	
	/**
     * Current status of the enquiry.
     * <p>
     * Example values: "NEW", "ENROLLED", "LOST". For stronger guarantees,
     * map this to an {@code EnquiryStatusEntity} or an enum in future iterations.
     * </p>
     */
	private String enquiryStatus;
	
	/**
     * Timestamp when the entity was created.
     * <p>
     * Automatically populated by Hibernate's {@code @CreationTimestamp}. Uses
     * {@link LocalDate} to record date-only information; if time-of-day is required,
     * consider switching to {@link java.time.LocalDateTime} or {@link java.time.OffsetDateTime}.
     * </p>
     */
	@CreationTimestamp
	private LocalDate createdDate;
	
	/**
     * Timestamp when the entity was last updated.
     * <p>
     * Automatically maintained by Hibernate's {@code @UpdateTimestamp}. Uses
     * {@link LocalDate} for date-only updates; change the type if a timestamp is needed.
     * </p>
     */
	@UpdateTimestamp
	private LocalDate updatedDate;
	
	/**
     * Many-to-one association to the user who created or owns this enquiry.
     * <p>
     * The database column {@code user_id} stores the foreign key. This association
     * links the enquiry to a {@code UserDetailsEntity}. Fetch strategy and cascade
     * behavior are not specified here and should be chosen based on use-case (for
     * example lazy loading to avoid eager joins when not required).
     * </p>
     */
	@ManyToOne
	@JoinColumn(name = "user_id")
	private UserDetailsEntity userDetailsEntity;
}
