package in.ansari.entity;

import java.util.List;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.Data;

/**
 * JPA entity representing application user details.
 * <p>
 * Mapped to the {@code USER_DETAILS} table, this entity holds authentication and
 * contact information for a user and models a one-to-many relationship to student
 * enquiries created or owned by the user.
 * </p>
 * <p>
 * Lombok's {@code @Data} generates standard getters, setters, {@code equals},
 * {@code hashCode} and {@code toString} implementations. Be mindful that
 * {@code toString} generated by Lombok will include fields by default; if the
 * list of enquiries can be large or contain sensitive data, consider excluding
 * it from {@code toString} or using a DTO for external exposure.
 * </p>
 */

@Entity
@Table(name = "USER_DETAILS")
@Data
public class UserDetailsEntity {

	/**
     * Primary key for the user record.
     * <p>
     * Generated by the persistence provider using {@link GenerationType#IDENTITY}.
     * Will be {@code null} for transient instances until persisted.
     * </p>
     */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer userId;
	
	/**
     * Unique username for authentication or display.
     * <p>
     * Should be validated for uniqueness and allowed character set at the service
     * or persistence layer; may be used as a login identifier depending on the
     * application's authentication strategy.
     * </p>
     */
	private String username;
	
	/**
     * User's email address.
     * <p>
     * Expected to follow a valid email format. Use validation annotations or
     * service-layer checks to enforce format and uniqueness if required.
     * </p>
     */
	private String userEmail;
	
	/**
     * Contact phone number for the user.
     * <p>
     * Stored as a {@link Long}. For international formats or leading zeros,
     * consider using a {@link String} with explicit formatting/validation rules.
     * </p>
     */
	private Long userPhoneNumber;
	
	/**
     * Encrypted password or password hash for the user.
     * <p>
     * This field must never store plain-text passwords. Ensure a secure hashing
     * algorithm (bcrypt, Argon2, etc.) is applied before persisting and that the
     * field is excluded from logs, toString output, and any API responses.
     * </p>
     */
	private String password;
	 
	/**
     * Account status indicator for the user.
     * <p>
     * Typical values might include "LOCKED" and "UNLOCKED".
     * Consider modelling statuses as an enum or reference table for stronger
     * validation and clearer semantics.
     * </p>
     */
	private String accountStatus;
	
	/**
     * One-to-many association to this user's student enquiries.
     * <p>
     * Mapped by the {@code userDetailsEntity} field on {@code StudentEnquiryEntity}.
     * CascadeType.ALL means persist, merge, remove and other lifecycle operations
     * will propagate from the user to the enquiries. FetchType.EAGER requests that
     * enquiries be loaded with the user; consider switching to LAZY if the list
     * is large or not always needed to avoid performance issues.
     * </p>
     */
	@OneToMany(mappedBy = "userDetailsEntity", cascade = CascadeType.ALL, fetch = FetchType.EAGER)
	private List<StudentEnquiryEntity> studentEnquiryEntities;
}